// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/super-admin/SuperAdminDashboard.tsx": () => import("../components/mockups/super-admin/SuperAdminDashboard.tsx"),
  "./components/mockups/super-admin/SuperAdminOnboarding.tsx": () => import("../components/mockups/super-admin/SuperAdminOnboarding.tsx"),
  "./components/mockups/super-admin/SuperAdminRestaurants.tsx": () => import("../components/mockups/super-admin/SuperAdminRestaurants.tsx"),
  "./components/mockups/restaurant-app/AdminDashboard.tsx": () => import("../components/mockups/restaurant-app/AdminDashboard.tsx"),
  "./components/mockups/restaurant-app/AdminMenuManager.tsx": () => import("../components/mockups/restaurant-app/AdminMenuManager.tsx"),
  "./components/mockups/restaurant-app/AdminOrderDetail.tsx": () => import("../components/mockups/restaurant-app/AdminOrderDetail.tsx"),
  "./components/mockups/restaurant-app/AdminQRCodes.tsx": () => import("../components/mockups/restaurant-app/AdminQRCodes.tsx"),
  "./components/mockups/restaurant-app/CustomerCart.tsx": () => import("../components/mockups/restaurant-app/CustomerCart.tsx"),
  "./components/mockups/restaurant-app/CustomerMenu.tsx": () => import("../components/mockups/restaurant-app/CustomerMenu.tsx"),
  "./components/mockups/restaurant-app/CustomerPayment.tsx": () => import("../components/mockups/restaurant-app/CustomerPayment.tsx"),
  "./components/mockups/restaurant-app/RestaurantWelcome.tsx": () => import("../components/mockups/restaurant-app/RestaurantWelcome.tsx")
};
